/**
 * Stable machine-readable codes for evidence rows, `<step>.<meaning>`.
 *
 * Every row the pipeline emits carries one of these in `code`, plus the values it
 * interpolated into its English `title`/`detail` in `params`, so a client (console,
 * mobile app, SDK) can render the row in any language without parsing English.
 * The English `title`/`detail` remain the normative text and never change here.
 */
export const EVIDENCE_CODES = [
  "request.parsed",
  "identity.federated_attestation_invalid",
  "identity.federated_attestation_subject",
  "identity.federated_attestation_action",
  "identity.federated_attestation_request_hash",
  "identity.federated_attestation_audience",
  "identity.federated",
  "identity.federation_level_insufficient",
  "identity.unknown",
  "identity.lifecycle",
  "identity.resolved",
  "credential.federated_issuer",
  "credential.presented_invalid",
  "credential.presented_subject",
  "credential.svid_verified",
  "credential.token_verified",
  "credential.missing",
  "credential.expired",
  "credential.issuer_untrusted",
  "credential.fresh",
  "proof.federated_skipped",
  "proof.invalid",
  "proof.issuer_mismatch",
  "proof.verified",
  "proof.unsigned_required",
  "proof.unsigned",
  "attestation_token.no_resolver",
  "attestation_token.invalid",
  "attestation_token.subject",
  "attestation_token.action",
  "attestation_token.resource",
  "attestation_token.audience",
  "attestation_token.request_hash",
  "attestation_token.revoked",
  "attestation_token.valid",
  "single_use.no_store",
  "single_use.consumed",
  "single_use.recorded",
  "principal.federated",
  "principal.federated_none",
  "principal.bound",
  "principal.unbound",
  "delegation.federated",
  "delegation.federated_none",
  "delegation.chain_invalid",
  "delegation.link_expired",
  "delegation.link_revoked",
  "delegation.link_outside_window",
  "delegation.valid",
  "delegation.none",
  "capability.missing",
  "capability.granted",
  "constraints.violated",
  "constraints.budget_exhausted",
  "constraints.budget_ok",
  "constraints.satisfied",
  "revocation.peer_unchecked",
  "revocation.peer_none",
  "revocation.peer_revoked",
  "revocation.peer_unreachable",
  "revocation.peer_unreachable_stale_ok",
  "revocation.agent",
  "revocation.credential",
  "revocation.delegation",
  "revocation.none",
  "attestation.present",
  "attestation.none",
  "enforcement.custody",
  "enforcement.attested",
  "enforcement.none",
  "policy.allow",
  "policy.deny",
  "policy.require_approval",
  "policy.approved_by_attestation",
  "policy.none",
  "registry.snapshot",
] as const;

export type EvidenceCode = (typeof EVIDENCE_CODES)[number];

/** Primitive values only: params travel as JSON in decisions, ledger events and API responses. */
export type EvidenceParams = Record<string, string | number | boolean | null>;

/**
 * The parameter names each code may carry (a value may be `null` when the request
 * had no such field). Message catalogues may only reference these placeholders.
 */
export const EVIDENCE_PARAMS: Record<EvidenceCode, readonly string[]> = {
  "request.parsed": ["action", "resource", "amount", "currency"],
  "identity.federated_attestation_invalid": ["issuer", "reason"],
  "identity.federated_attestation_subject": ["sub"],
  "identity.federated_attestation_action": ["action", "resource"],
  "identity.federated_attestation_request_hash": ["jti"],
  "identity.federated_attestation_audience": ["aud", "expected"],
  "identity.federated": ["peer", "level", "issuer", "sub"],
  "identity.federation_level_insufficient": ["peer", "issuer"],
  "identity.unknown": ["agent"],
  "identity.lifecycle": ["lifecycle"],
  "identity.resolved": ["stable_id"],
  "credential.federated_issuer": ["peer", "issuer"],
  "credential.presented_invalid": ["reason", "issuer"],
  "credential.presented_subject": ["sub"],
  "credential.svid_verified": ["kind", "issuer", "kid", "exp"],
  "credential.token_verified": ["kind", "issuer", "kid", "exp"],
  "credential.missing": [],
  "credential.expired": ["not_after"],
  "credential.issuer_untrusted": ["issuer"],
  "credential.fresh": ["kind", "not_after"],
  "proof.federated_skipped": [],
  "proof.invalid": ["reason", "kid"],
  "proof.issuer_mismatch": ["iss", "kid"],
  "proof.verified": ["alg", "kid"],
  "proof.unsigned_required": [],
  "proof.unsigned": [],
  "attestation_token.no_resolver": [],
  "attestation_token.invalid": ["reason"],
  "attestation_token.subject": ["sub"],
  "attestation_token.action": ["action"],
  "attestation_token.resource": ["resource"],
  "attestation_token.audience": ["aud", "expected"],
  "attestation_token.request_hash": ["jti"],
  "attestation_token.revoked": ["jti"],
  "attestation_token.valid": ["jti", "expires_in", "issuer", "action", "human_approved"],
  "single_use.no_store": ["jti"],
  "single_use.consumed": ["jti"],
  "single_use.recorded": ["jti"],
  "principal.federated": ["principal", "peer"],
  "principal.federated_none": [],
  "principal.bound": ["name", "id"],
  "principal.unbound": [],
  "delegation.federated": ["links"],
  "delegation.federated_none": [],
  "delegation.chain_invalid": ["reason", "at"],
  "delegation.link_expired": ["link", "status"],
  "delegation.link_revoked": ["link", "status"],
  "delegation.link_outside_window": ["link", "status"],
  "delegation.valid": ["links"],
  "delegation.none": [],
  "capability.missing": ["action", "resource"],
  "capability.granted": ["action", "resource"],
  "constraints.violated": ["limits"],
  "constraints.budget_exhausted": ["spent", "total", "left", "currency"],
  "constraints.budget_ok": ["used", "total", "left", "currency"],
  "constraints.satisfied": ["limits"],
  "revocation.peer_unchecked": ["peer", "expires_in"],
  "revocation.peer_none": ["peer", "jti"],
  "revocation.peer_revoked": ["peer", "jti"],
  "revocation.peer_unreachable": ["peer", "age", "stale_ok"],
  "revocation.peer_unreachable_stale_ok": ["peer", "age", "stale_ok"],
  "revocation.agent": ["ref"],
  "revocation.credential": ["ref"],
  "revocation.delegation": ["ref"],
  "revocation.none": [],
  "attestation.present": ["kinds"],
  "attestation.none": [],
  "enforcement.custody": ["path"],
  "enforcement.attested": ["path"],
  "enforcement.none": ["path"],
  "policy.allow": ["fired", "version"],
  "policy.deny": ["fired", "version"],
  "policy.require_approval": ["fired", "version"],
  "policy.approved_by_attestation": ["fired", "version", "jti", "approval_id"],
  "policy.none": [],
  "registry.snapshot": ["age"],
};

export const isEvidenceCode = (v: unknown): v is EvidenceCode => typeof v === "string" && (EVIDENCE_CODES as readonly string[]).includes(v);
